config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'homes#index'

  resources :photos do
    member do
      post 'like'
      post 'unlike'
    end
    resources :comments, only: [:create]
  end
  resources :users

  resources :homes, only: %i[index show] do
    member do
      post 'follow'
      delete 'unfollow'
      post 'send_request'
      delete 'cancel_request'
      patch 'accept_request'
      patch 'reject_request'
      match 'like_photo', via: %i[post get]
    end
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

# Top-level documentation home for HomesController
class HomesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @pending_requests = find_pending_requests(@user)
    @photos = @user.photos
    @follower_count = count_accepted_followers(@user)
    @following_count = count_accepted_followings(@user)
    render_show_page
  end

  def like_photo
    @user = User.find(params[:id])
    @liked_photos = Photo.joins(:likes).where(likes: { user_id: @user.id })
  end

  def send_request
    @user = User.find(params[:id])
    return send_private_request if @user.private?

    send_accepted_request
  end

  def cancel_request
    followed_user = User.find(params[:id])
    following = current_user.followings.find_by(followed_user: followed_user, status: 'pending')
    if following
      following.destroy
      redirect_to user_path(followed_user), notice: "Follow request canceled for #{followed_user.username}."
    else
      redirect_to user_path(followed_user), alert: "No pending follow request found for #{followed_user.username}."
    end
  end

  def accept_request
    follower = User.find(params[:id])
    following = follower.followings.find_by(followed_user: current_user, status: 'pending')
    if following
      following.update(status: 'accepted')
      redirect_to user_path(current_user), notice: "You have accepted the follow request from #{follower.username}."
    else
      redirect_to user_path(current_user), alert: "No pending follow request found from #{follower.username}."
    end
  end

  def reject_request
    follower = User.find(params[:id])
    following = follower.followings.find_by(followed_user: current_user, status: 'pending')
    if following
      following.destroy
      redirect_to user_path(current_user), notice: "You have rejected the follow request from #{follower.username}."
    else
      redirect_to user_path(current_user), alert: "No pending follow request found from #{follower.username}."
    end
  end

  def unfollow
    followed_user = User.find(params[:id])
    following = current_user.followings.find_by(followed_user_id: followed_user.id, status: 'accepted')
    if following
      following.destroy
      redirect_to user_path(followed_user), notice: "You have unfollowed #{followed_user.username}."
    else
      redirect_to user_path(followed_user), alert: "You were not following #{followed_user.username}."
    end
  end

  private

  def render_show_page
    if !user_signed_in?
      redirect_to new_user_session_path, notice: 'Please sign in to view details.'
    elsif authorized_user? || !@user.private?
      render 'show'
    else
      redirect_to root_path, alert: "You're not authorized to view this user's details."
    end
  end

  def find_pending_requests(user)
    Following.where(followed_user: user, status: 'pending').includes(:follower)
  end

  def count_accepted_followers(user)
    Following.where(followed_user_id: user.id, status: 'accepted').count
  end

  def count_accepted_followings(user)
    Following.where(follower_id: user.id, status: 'accepted').count
  end

  def authorized_user?
    current_user == @user || current_user.followings.exists?(followed_user_id: @user.id)
  end

  def send_private_request
    following = current_user.followings.build(followed_user: @user, follower_id: current_user.id, status: 'pending')
    if following.save
      redirect_to @user, notice: 'Follow request sent.'
    else
      redirect_to @user, alert: 'Failed to send follow request.'
    end
  end

  def send_accepted_request
    following = current_user.followings.build(followed_user: @user, status: 'accepted')
    if following.save
      redirect_to home_path, notice: 'You are now following.'
    else
      redirect_to home_path(@user), alert: 'Failed to follow.'
    end
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Module to provide helper methods for the home
module HomeHelper
end

app/views/homes/index.html.erb
<h1> List of user </h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">UserName</th>
      <th scope="col">Private ?</th>
      <th scope="col">   </th>
      <th scope="col">   </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th><%= user.username %></th>
        <td><%= user.private ? 'Yes' : 'No' %></td>
        <td><% if user_signed_in? %>
        <% if current_user == user %>
          <%= button_to "Follow", home_path(user.id), method: :get %> 
        <% elsif current_user.followings.exists?(followed_user_id: user.id) %>
          <% following = current_user.followings.find_by(followed_user_id: user.id) %>
          <% if following.status == "accepted" %>
            <%= button_to "Unfollow", unfollow_home_path(user.id), method: :delete %>
          <% elsif following.status == "pending" %>
            <%= button_to "Cancel Request", cancel_request_home_path(user.id), method: :delete %>
          <% end %>
        <% else %>
          <% if user.private? %>
            <% following = current_user.followings.find_by(followed_user_id: user.id) %>
            <% if following && following.status == "pending" %>
              <%= button_to "Cancel Request", cancel_request_home_path(user.id), method: :delete %>
            <% else %>
              <%= button_to "Follow", send_request_home_path(user.id), method: :post %>
            <% end %>
          <% else %>
            <%= button_to "Follow", send_request_home_path(user.id), method: :post %>
          <% end %>
        <% end %>
      <% end %>
      </td> 
      <td><%= link_to "Show details", home_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/homes/like_photo.html.erb
<h1>Liked Photos</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Image</th>
      <th scope="col">Caption</th>
      <th scope="col">Owner</th>
      <th scope="col">Posted</th>
      <th scope="col">Likes</th>
      <th scope="col">      </th>
    </tr>
  </thead>
  <tbody>
    <% @liked_photos.each do |photo| %>
      <tr>
        <td><%= image_tag photo.image, style: "width: 200px; display: block" %></td>
        <td><%= photo.caption %></td>
        <td><%= photo.user&.username %></td>
        <td><%= time_ago_in_words(photo.created_at) %> ago</td>
        <td><%= photo.like_count %></td>
        <td><%= link_to "Show details", photo_path(photo.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/homes/show.html.erb
<h1>User Details</h1>
<p>Username: <%= @user.username %></p>
<p>Private Account: <%= @user.private ? 'Yes' : 'No' %></p>
<p>Followers :<%= @follower_count %></p>

<% if current_user == @user %>
  <% @pending_requests.each do |request| %>
    <% if request.follower != current_user && request.status == "pending" %>
      <div>
        <%= link_to request.follower.username, user_path(request.follower) %> has sent you a follow request.
        <%= button_to "Accept", accept_request_home_path(request.follower), method: :patch %>
        <%= button_to "Reject", reject_request_home_path(request.follower), method: :delete %>
      </div>
    <% end %>
  <% end %>
<% end %>
<p>Following :<%= @following_count %></p>

<h1>Own Photos</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Image</th>
      <th scope="col">Caption</th>
      <th scope="col">Owner</th>
      <th scope="col">Posted</th>
      <th scope="col">Likes</th>
      <th scope="col">      </th>
    </tr>
  </thead>
  <tbody>
    <% @user.photos.each do |photo| %>
      <tr>
        <td><%= image_tag photo.image, style: "width: 200px; display: block" %></td>
        <td><%= photo.caption %></td>
        <td><%= photo.user&.username %></td>
        <td><%= time_ago_in_words(photo.created_at) %> ago</td>
        <td><%= photo.like_count %></td>
        <td><%= link_to "Show details", photo_path(photo.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Liked Photos", like_photo_home_path(@user) %>