config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'homes#index'

  resources :photos do
    member do
      post 'like'
      post 'unlike'
    end
    resources :comments, only: [:create]
  end
  resources :users

  resources :homes, only: %i[index show] do
    member do
      post 'follow'
      delete 'unfollow'
      post 'send_request'
      delete 'cancel_request'
      patch 'accept_request'
      patch 'reject_request'
      match 'like_photo', via: %i[post get]
    end
  end
end

app/models/photo.rb
# frozen_string_literal: true

# Represents a photo model
class Photo < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes
  has_many :comments

  scope :public_photos, -> { where(public: true) }
  def comments_count
    comments.count
  end
end

app/controllers/photos_controller.rb
# frozen_string_literal: true

# Controller for managing photos.
class PhotosController < ApplicationController
  def index
    @public_users = User.where(private: false)
    @public_photos = Photo.where(user: @public_users)
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user
    if @photo.save
      redirect_to photos_path, notice: 'Photo was successfully uploaded.'
    else
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def like
    @photo = Photo.find(params[:id])
    current_user.likes.create(photo: @photo) unless current_user.likes.exists?(photo: @photo)
    @photo.increment!(:like_count)
    redirect_to @photo, notice: 'Photo liked successfully.'
  end

  def unlike
    @photo = Photo.find(params[:id])
    like = current_user.likes.find_by(photo: @photo)
    like.destroy if like.present?
    @photo.decrement!(:like_count)
    redirect_to @photo, notice: 'Photo unliked successfully.'
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :image)
  end
end

app/helpers/photos_helper.rb
# frozen_string_literal: true

# Module to provide helper methods for the photo
module PhotosHelper
end

app/views/photos/index.html.erb
<%= form_with(model: @photo, url: photos_path, method: :post, local: true) do |form| %>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption %>
  </div>

  <%= form.submit %>
<% end %>

<h1>List of Photos</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Image</th>
      <th scope="col">Caption</th>
      <th scope="col">Owner</th>
      <th scope="col">Posted</th>
      <th scope="col">Likes</th>
      <th scope="col">      </th>
    </tr>
  </thead>
  <tbody>
    <% @public_photos.each do |photo| %>
      <tr>
        <td><%= image_tag photo.image, style: "width: 200px; display: block" %></td>
        <td><%= photo.caption %></td>
        <td><%= photo.user&.username %></td>
        <td><%= time_ago_in_words(photo.created_at) %> ago</td>
        <td><%= photo.like_count %></td>
        <td><%= link_to "Show details", photo_path(photo.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/photos/show.html.erb
<h1>Photo Details</h1>
<p>Image: <%= image_tag @photo.image, style: "width: 200px; display: block" %></p>
<p>Caption: <%= @photo.caption%></p>
<p>Owner: <%= @photo.user&.username%></p>
<p>Posted: <%= time_ago_in_words(@photo.created_at) %> ago</p>
<p>Like Count: <%= @photo.like_count %></p>
<p>Comments Count : <%= @photo.comments_count %></p>
<p>Fan</p>
<% if @photo.likes.any? %>
  <ul>
    <% @photo.likes.each do |like| %>
      <li><%= like.user.username %></li>
    <% end %>
  </ul>
<% else %>
  <p>No likes yet.</p>
<% end %>
<p>Add Fan</p> 
<% if current_user.likes.exists?(photo_id: @photo.id) %>
  <%= button_to 'Unlike', unlike_photo_path(@photo), method: :post %>
<% else %>
  <%= button_to 'Like', like_photo_path(@photo), method: :post %>
<% end %></p>

<h1>Comments</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Commenter</th>
      <th scope="col">Comment</th>
      <th scope="col">Posted</th>
    </tr>
  </thead>
  <tbody>
    <% @photo.comments.each do |comment| %>
      <tr>
        <td><%= comment.user.username %></td>
        <td><%= comment.body %></td>
        <td><%= time_ago_in_words(comment.created_at) %> ago</td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Add a new Comment</h2>
<%= form_with(model: [@photo, Comment.new], url: photo_comments_path(@photo)) do |form| %>
  <%= form.text_area :body, placeholder: 'Enter your comment' %>
  <%= form.submit 'Add Comment' %>
<% end %>