config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'homes#index'

  resources :photos do
    member do
      post 'like'
      post 'unlike'
    end
    resources :comments, only: [:create]
  end
  resources :users

  resources :homes, only: %i[index show] do
    member do
      post 'follow'
      delete 'unfollow'
      post 'send_request'
      delete 'cancel_request'
      patch 'accept_request'
      patch 'reject_request'
      match 'like_photo', via: %i[post get]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'all user', root_path, class: 'nav-link'  %>
      </li>
      <li class="nav-item">
        <%= link_to 'all public photos', photos_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to current_user.username, edit_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to 'all user', root_path, class: 'nav-link'  %>
      </li>
      <li class="nav-item">
        <%= link_to 'all public photos', photos_path, class: 'nav-link'  %>
      </li>
      <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
      </li>
    <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
  </body>
</html>